estate/urls.py
from django.urls import path
from .views import dashboard, investments, other_assets, investment_details, property_details, assets, exchange, transfer

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('details/<int:property_id>/', property_details, name='property_details'),
    path('investments/', investments, name='investments'),
    path('investments/<int:investment_id>/', investment_details, name='investment_details'),
    path('other_assets/', other_assets, name='other_assets'),
    path('assets/', assets, name='assets'),
    path('exchange/', exchange, name='exchange'),
    path('transfer/', transfer, name='transfer'),
    # Add more paths as needed
]

main_p/urls.py
# main_p/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('static_pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('estate.urls')),
    path('payment/', include('payment.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estate/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from payment.models import Funds

class Property(models.Model):
    CHOICES_FOR_SELL_RENT = [
        ('For Sell', 'For Sell'),
        ('For Rent', 'For Rent'),
    ]

    CHOICES_PROPERTY_PURPOSE = [
        ('Apartment', 'Apartment'),
        ('Villa', 'Villa'),
        ('Building', 'Building'),
        ('Townhouse', 'Townhouse'),
        ('Home', 'Home'),
        ('Shop', 'Shop'),
        ('Office', 'Office'),
        ('Garage', 'Garage'),
    ]

    tag = models.CharField(max_length=20, choices=CHOICES_FOR_SELL_RENT)
    image = models.ImageField(upload_to='property_images/')
    purpose = models.CharField(max_length=20, choices=CHOICES_PROPERTY_PURPOSE)
    title = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    width_in_sqft = models.FloatField()
    no_of_bed = models.PositiveIntegerField(null=True, blank=True)
    no_of_bath = models.PositiveIntegerField(null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True) 

    class Meta:
        verbose_name_plural = "Properties"
        ordering = ['-created_at'] 

    def __str__(self):
        return self.title

class PropertyStatus(models.Model):
    CHOICES_PROPERTY_STATUS = [
        ('Fast Growing', 'Fast Growing'),
        ('Hot Assets', 'Hot Assets'),
        ('Most Invested', 'Most Invested'),
    ]

    status = models.CharField(max_length=20, choices=CHOICES_PROPERTY_STATUS)
    investors_count = models.PositiveIntegerField()
    property = models.ManyToManyField(Property)

    class Meta:
        verbose_name_plural = "Property Statuses"
        ordering = ['status']

    def __str__(self):
        return self.status

class Investment(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    interest_percentage = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True) 
    account_type = models.CharField(max_length=20, choices=Funds.ACCOUNT_TYPES)  # Link to your existing Funds model

    class Meta:
        verbose_name_plural = "Investments"
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        # Calculate interest_percentage based on the amount invested
        if self.amount >= 90000:
            self.interest_percentage = 50
        elif self.amount >= 40000:
            self.interest_percentage = 30
        else:
            self.interest_percentage = 15

        super().save(*args, **kwargs)

    def __str__(self):
        return f"Investment of {self.user.username} in {self.property.title}"

class CloseInvestment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    wallet_address = models.CharField(max_length=255)
    network = models.CharField(max_length=50, default="TRC20")

    def __str__(self):
        return f"Closed Investment for {self.user.username} - {self.property.title} - {self.wallet_address}"

    class Meta:
        verbose_name_plural = "Closed Investments"

templates/dashboard_T/assets.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Assets{% endblock %}

{% block content %}
<div class="app-body-main-content">
    <section class="transfer-section">
        
        <div class="transfer-section-header">
            <h2 style="margin-bottom: 15px;">Assets</h2>
        </div>

        <!-- Property List Start -->
        <div class="container-xxl py-5" style="max-width:600px;">
            <div class="container">
                
                <div class="tab-content">
                    <div id="tab-1" class="tab-pane fade show p-0 active">
                        <div class="row g-4">
                            {% for property in properties %}
                            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="property-item rounded overflow-hidden">
                                    <div class="position-relative overflow-hidden">
                                        <a href="{% url 'property_details' property.id %}">
                                            <img class="img-fluid" src="{{ property.image.url }}" alt="{{ property.title }}">
                                        </a>
                                        <div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">
                                            {% if property.tag == 'For Sell' %}For Sell{% else %}For Rent{% endif %}
                                        </div>
                                        <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">{{ property.purpose }}</div>
                                    </div>
                                    <div class="p-4 pb-0">
                                        <h5 class="text-primary mb-3">{{ property.amount }}</h5>
                                        <a class="d-block h5 mb-2" href="{% url 'property_details' property.id %}">{{ property.title }}</a>
                                        <p><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ property.address }}</p>
                                    </div>
                                    <div class="d-flex border-top">
                                        <small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>{{ property.width_in_sqft }} Sqft</small>
                                        <small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>{{ property.no_of_bed }} Bed</small>
                                        <small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>{{ property.no_of_bath }} Bath</small>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
        <!-- Property List End -->

    </section>
</div>

{% comment %} don't touch {% endcomment %}
{% include 'chunks/side_balance.html' %}

{% endblock content %}

templates/dashboard_T/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="app-body-main-content" style="max-width:600px;">
    <section class="transfer-section">
        {% for property_status in property_statuses %}
            <div>
                <div class="transfer-section-header">
                    <h2 style="margin-bottom: 15px;">{{ property_status.status }}</h2>
                </div><br>
                <div class="row g-4">
                    {% for property in property_status.property.all %}
                        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                            <div class="property-item rounded overflow-hidden">
                                <div class="position-relative overflow-hidden">
                                    <a href="{% url 'property_details' property.id %}">
                                        <img class="img-fluid" src="{{ property.image.url }}" alt="{{ property.title }}">
                                    </a>
                                    <div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">
                                        {% if property.tag == 'For Sell' %}For Sell{% else %}For Rent{% endif %}
                                    </div>
                                    <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">{{ property.purpose }}</div>
                                </div>
                                <div class="p-4 pb-0">
                                    <h5 class="text-primary mb-3">{{ property.amount }}</h5>
                                    <a class="d-block h5 mb-2" href="{% url 'property_details' property.id %}">{{ property.title }}</a>
                                    <p><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ property.address }}</p>
                                </div>
                                <div class="d-flex border-top">
                                    <small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>{{ property.width_in_sqft }} Sqft</small>
                                    <small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>{{ property.no_of_bed }} Bed</small>
                                    <small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>{{ property.no_of_bath }} Bath</small>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div><br>
            </div>
        {% endfor %}
    </section>
</div>

{% comment %} don't touch {% endcomment %}
{% include 'chunks/side_balance.html' %}

{% endblock content %}

templates/dashboard_T/exchange.html
{% extends 'base.html' %}

{% block title %}Exchange{% endblock %}

{% block content %}
<div class="app-body-main-content">
    <section class="transfer-section">
        
        <div class="transfer-section-header">
            <h2 style="margin-bottom: 15px;">Investment Guide</h2>
        </div>

        <div class="transfers" id="investment-guide-container" style="max-width:700px;">
            <p>Welcome to Provex Homes! Here's a step-by-step guide on how to invest in assets and grow your portfolio:</p>

            <ol>
                <li><strong>Login:</strong> Sign in to your account using your credentials.</li>

                <li>
                    <strong>Fund Your Wallet:</strong> Navigate to the "Transfer" section, where you will find three wallet addresses for BTC, USDT TRC20, and ERC20. Choose any of them based on your preference and fund your wallet accordingly.
                    <ul>
                        <li>Enter the amount you want to fund.</li>
                        <li>Provide the wallet address if you are funding with USDT, BTC, or ERC20.</li>
                        <li>Wait for network confirmation.</li>
                        <li>Your account balance will be updated after confirmation.</li>
                    </ul>
                </li>

                <li>
                    <strong>Explore Assets:</strong> Head to the dashboard and locate the "Assets" section. Here, you'll find a list of available properties to invest in.
                    <ul>
                        <li>Click on the title or image of any property to view its details.</li>
                    </ul>
                </li>

                <li>
                    <strong>Invest in a Property:</strong> On the property details page, scroll down to find the investment form.
                    <ul>
                        <li>Enter the amount you wish to invest in the property.</li>
                        <li>Click the "Invest" button.</li>
                    </ul>
                </li>

                <li>
                    <strong>View Your Investments:</strong> After investing, you can check your investment details on the investment page.
                    <ul>
                        <li>View the assets you've invested in.</li>
                        <li>See your interest, percentages, and more.</li>
                    </ul>
                </li>
            </ol>

            <p>Feel free to explore different properties and diversify your investments. If you have any questions, our support team is here to assist you.</p>
        </div>
    </section>
</div>

{% comment %} don't touch {% endcomment %}
{% include 'chunks/side_balance.html' %}

{% endblock content %}

templates/dashboard_T/property_details.html
{% extends 'base.html' %}

{% block title %}Property Details{% endblock %}

{% block content %}
<div class="app-body-main-content container-md">
    <section class="transfer-section">
        <div>
            <div class="transfers" id="property-details-container">
                <div style="margin-bottom: 20px;">
                    <img src="{{ property.image.url }}" alt="{{ property.title }}" style="border-radius: 10px; max-width: 100%;"><br>
                    <h3>{{ property.title }}</h3>
                    <p><strong>Address:</strong> {{ property.address }}</p>
                    <p><strong>Width (sqft):</strong> {{ property.width_in_sqft }}</p>
                    <p><strong>Number of Bedrooms:</strong> {{ property.no_of_bed }}</p>
                    <p><strong>Number of Bathrooms:</strong> {{ property.no_of_bath }}</p>
                    <p><strong>Amount ($):</strong> {{ property.amount }}</p>
                    <p><strong>For:</strong> {{ property.tag }}</p>
                    <p><strong>Purpose:</strong> {{ property.get_purpose_display }}</p>
                </div>
            </div>
        </div>

        <br>
        <form method="POST" action="{% url 'property_details' property.id %}">
            {% csrf_token %}
            <div class="faq" style="max-width:700px;">
                <p>Enter the amount you wish to invest on this asset</p>
                <div>
                    <label>Amount</label>
                    <input type="text" name="amount" placeholder="Type here">
                </div>
                <div>
                    <label>Wallet</label>
                    <select name="account_type">
                        <option value="USDT_TRC20">USDT TRC20</option>
                        <option value="USDT_ERC20">USDT ERC20</option>
                        <option value="BTC">BTC</option>
                    </select>
                </div>
            </div>
            <div class="payment-section-footer">
                <button class="save-button" style="width:100%;" type="submit">
                    Invest
                </button>
            </div>
        </form>
        
    </section>
</div>

{% comment %} don't touch {% endcomment %}
{% include 'chunks/side_balance.html' %}

{% endblock content %}

templates/dashboard_T/transfer.html
{% extends 'base.html' %}

{% block title %}Transfer{% endblock %}

{% block content %}
<div class="app-body-main-content">
    <section class="service-section">
        
        <!-- search by category (high, medium, low returns) -->
        <div class="mobile-only">
            <button class="flat-button">
                Funding Addresses
            </button>
        </div>
        
        <div class="container mt-4">
            <div class="row">
                <div class="col-md-12">
                    <div class="tiles">
                        {% for address in latest_addresses %}
                            <article class="tile" style="max-width:210px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                                <div class="tile-header">
                                    <i class="{{ address.coin_icon }}"></i>
                                    <h3>
                                        <span>{{ address.coin_name }}</span>
                                        <span>{{ address.wallet_address }}</span>
                                        <button style="max-width:160px;" class="btn btn-outline-dark btn-sm ml-2 copy-address" data-address="{{ address.wallet_address }}">Copy</button>
                                    </h3>
                                </div>
                                <span class="d-block text-center">
                                    <img src="{{ address.qr_code.url }}" alt="QRCode" width="180" height="auto">
                                </span>
                            </article>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="service-section-footer">
            <p>Choose any payment address you wish to use and make payment</p>
        </div>
    </section>

    
    <br>
    <div class="transfer-section-header">
        <h2 style="margin-bottom: 15px;">Fund Wallet</h2>
    </div>

    <form method="POST" action="{% url 'add_funds' %}">
        {% csrf_token %}
        <div class="faq" style="max-width:700px;">
            <p>Enter the exact amount you want to fund your wallet with, and the wallet you wish to fund with (BTC, USDT, or ETH), don't put the wrong amount to avoid loss of funds. Your account will be updated upon confirmation</p>
            <div>
                <label>Amount</label>
                <input type="text" name="amount" placeholder="Type here">
            </div>
            <div>
                <label>Wallet</label>
                <select name="account_type">
                    <option value="USDT_TRC20">USDT TRC20</option>
                    <option value="USDT_ERC20">USDT ERC20</option>
                    <option value="BTC">BTC</option>
                </select>
            </div>
        </div>
        <div class="payment-section-footer">
            <button class="save-button" style="width:100%;" type="submit">
                Fund
            </button>
        </div>
    </form>

</div>

{% comment %} don't touch {% endcomment %}
{% include 'chunks/side_balance.html' %}

<script>
    // Add event listener to each copy-address button
    document.querySelectorAll('.copy-address').forEach(function (button) {
        button.addEventListener('click', function () {
            // Find the corresponding wallet address
            const walletAddress = this.getAttribute('data-address');

            // Copy wallet address to clipboard
            navigator.clipboard.writeText(walletAddress);

            // Show tooltip
            tippy(this, {
                content: 'Wallet Address Copied!',
                trigger: 'manual',
                placement: 'top',
            }).show();

            // Hide tooltip after a short delay
            setTimeout(function () {
                tippy(this).hide();
            }, 2000);
        });
    });
</script>

{% endblock content %}